version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # install Node 12
      - echo installing node 12..
      - curl -fsSL https://deb.nodesource.com/setup_12.x | -E bash -
      - apt install -y nodejs
  pre_build:
    commands:
      # install dependencies
      - echo Installing NPM dependencies...
      - npm install
      - echo NPM dependencies installed.
  build:
    commands:
      # build
      - echo Building environment.
      - npm run build
      - echo environment ready.
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  discard-path: no
  base-directory: build
