version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12  
    commands:
      - echo Initiating build. 
      - echo Stand by...
  pre_build:
    commands:
      - echo %%%%%Installing NPM dependencies...
      - npm install
      - echo NPM dependencies installed.
  build:
    commands:
      - echo Building environment.
      - npm run build
      - echo environment ready.
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/**/*
    - Procfile
    - server.compiled.js
    - package.json